apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: node-11625 
  janus-idp.io/tekton: node-11625
  backstage.io/kubernetes-id: node-11625
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: node-11625
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml