apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: node-11625
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-11625 
  name: node-11625
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: node-11625
    weight: 100 
